# Generated by Django 5.1.2 on 2024-10-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('picture', models.URLField()),
                ('post_code', models.CharField(max_length=10)),
                ('registered_date', models.DateTimeField()),
                ('username', models.CharField(max_length=50)),
            ],
        ),
    ]
